name: CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: echo "test complete"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: echo "build complete"
