name: Receive PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - "*"

jobs:
  confirm:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON(github) }}
      - run: |
          if [[ ${LABEL_PRESENT-false} == "false" ]]; then
            echo "missing 'approve-ci' label"
          fi
        env:
          LABEL_PRESENT: ${{ contains(github.event.labels.*.name, 'approve-ci') }}
