name: Receive PR

on:
  pull_request_target:
    branches:
      - "*"

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON(github) }}

  request-approval:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    environment: test
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON(github) }}
