name: Receive PR

on:
  pull_request_target:
    branches:
      - main

jobs:
  check-external:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    environment: test
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON(github) }}

  run-ci:
    needs: check-external
    runs-on: ubuntu-latest
    steps:
      - uses: Dynatrace/dynatrace-operator/.github/workflows/ci.yml@main
        secrets: inherit
