name: Receive PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - "*"

jobs:
  confirm:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.labels.*.name, 'approve-ci') }}
    environment: test
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON(github) }}
